# Generated by Django 4.2.3 on 2023-07-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_user',
            old_name='comfirm_password',
            new_name='confirm_password',
        ),
    ]
