# Generated by Django 4.2.3 on 2023-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_comfirm_password_super_user_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='superduper_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
